### ISSUE TITLE
incorrect result for hierseg with family=normal and lambda=0

### ISSUE THREAD

**Issue by tdhock** [Lucas-Prates/blockcpd#6]
hi @Lucas-Prates I expected based on the documentation that family=normal means the normal change in both mean and variance model. In this model there is a segment/block-specific variance parameter, which requires at least two unique data points to estimate. I therefore expected no segments of size one data point, but I observed that when lambda=0:
```r
> blockcpd::fit_blockcpd(t(matrix(0:3)), method="hierseg", family="normal", lambda=0)$changepoints
[1] 1 2 3
```
The result I expected in this case is changepoints=2 (no changepoint after 1 nor 3).

**Comment by Lucas-Prates** [comment]
@tdhock, thank you very much for raising this issue. The package was originally developed for multiple aligned series, so most of my tests were with more than one series. Indeed, I need to add unit testing.

The incorrect computation comes from evaluating log(0). I believe to have fixed this issue on commit 44, so you can test again if you want.

**Comment by tdhock** [comment]
great thanks.
```r
> remotes::install_github("Lucas-Prates/blockcpd@3235d0eb3f060998950711dbff735f33398c467d")
Skipping install of 'blockcpd' from a github remote, the SHA1 (3235d0eb) has not changed since last install.
  Use `force = TRUE` to force installation
> blockcpd::fit_blockcpd(t(matrix(0:3)), method="hierseg", family="normal", lambda=0)$changepoints
[1] 2
```
